// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `authentication` resource.

#[derive(Clone)]
pub struct Authentication {
    client: crate::client::ScalarGalaxyClient,
}

impl Authentication {
    pub(crate) fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self { client }
    }

    /// Create a user
    pub fn create_user(&self) -> CreateUserRequest {
        CreateUserRequest::new(self.client.clone())
    }

    /// Get a token
    pub fn create_token(&self) -> CreateTokenRequest {
        CreateTokenRequest::new(self.client.clone())
    }

    /// Get authenticated user
    pub fn list_me(&self) -> ListMeRequest {
        ListMeRequest::new(self.client.clone())
    }
}

/// Time to create a user account, eh?
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateUserRequest {
    client: crate::client::ScalarGalaxyClient,
    body: Option<crate::models::AuthenticationCreateUserBody>,
    idempotency_key: Option<String>,
}

impl CreateUserRequest {
    fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
        }
    }

    /// User to create
    pub fn body(mut self, value: crate::models::AuthenticationCreateUserBody) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::User, crate::error::Error> {
        let path = "/user/signup".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        self.client
            .send::<crate::models::User, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Yeah, this is the boring security stuff. Just get your super secret token and move on.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateTokenRequest {
    client: crate::client::ScalarGalaxyClient,
    body: Option<crate::models::Credentials>,
    idempotency_key: Option<String>,
}

impl CreateTokenRequest {
    fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
        }
    }

    /// Credentials to authenticate a user
    pub fn body(mut self, value: crate::models::Credentials) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Token, crate::error::Error> {
        let path = "/auth/token".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        self.client
            .send::<crate::models::Token, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Find yourself they say. That's what you can do here.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListMeRequest {
    client: crate::client::ScalarGalaxyClient,
}

impl ListMeRequest {
    fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self {
            client,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::User, crate::error::Error> {
        let path = "/me".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::User, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
