// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `celestialBodies` resource.

#[derive(Clone)]
pub struct CelestialBodies {
    client: crate::client::ScalarGalaxyClient,
}

impl CelestialBodies {
    pub(crate) fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self { client }
    }

    /// Create a celestial body
    pub fn create(&self, body: crate::models::CelestialBody) -> CreateRequest {
        CreateRequest::new(self.client.clone(), body)
    }
}

/// Create a celestial body
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::ScalarGalaxyClient,
    body: crate::models::CelestialBody,
    idempotency_key: Option<String>,
}

impl CreateRequest {
    fn new(client: crate::client::ScalarGalaxyClient, body: crate::models::CelestialBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::CelestialBody, crate::error::Error> {
        let path = "/celestial-bodies".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::CelestialBody, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
