// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Resource sub-clients and root accessors.

pub mod planets;
pub mod celestial_bodies;
pub mod authentication;

impl crate::client::ScalarGalaxyClient {
    pub fn planets(&self) -> crate::resources::planets::Planets {
        crate::resources::planets::Planets::new(self.clone())
    }

    pub fn celestial_bodies(&self) -> crate::resources::celestial_bodies::CelestialBodies {
        crate::resources::celestial_bodies::CelestialBodies::new(self.clone())
    }

    pub fn authentication(&self) -> crate::resources::authentication::Authentication {
        crate::resources::authentication::Authentication::new(self.clone())
    }
}
