// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `planets` resource.

#[derive(Clone)]
pub struct Planets {
    client: crate::client::ScalarGalaxyClient,
}

impl Planets {
    pub(crate) fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self { client }
    }

    /// Get all planets
    pub fn list_all_data(&self) -> ListAllDataRequest {
        ListAllDataRequest::new(self.client.clone())
    }

    /// Create a planet
    pub fn create(&self) -> CreateRequest {
        CreateRequest::new(self.client.clone())
    }

    /// Get a planet
    pub fn retrieve(&self, planet_id: i64) -> RetrieveRequest {
        RetrieveRequest::new(self.client.clone(), planet_id)
    }

    /// Update a planet
    pub fn update(&self, planet_id: i64) -> UpdateRequest {
        UpdateRequest::new(self.client.clone(), planet_id)
    }

    /// Delete a planet
    pub fn delete(&self, planet_id: i64) -> DeleteRequest {
        DeleteRequest::new(self.client.clone(), planet_id)
    }

    /// Upload an image to a planet
    pub fn upload_image(&self, planet_id: i64) -> UploadImageRequest {
        UploadImageRequest::new(self.client.clone(), planet_id)
    }
}

/// It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListAllDataRequest {
    client: crate::client::ScalarGalaxyClient,
    limit: Option<i64>,
    offset: Option<i64>,
}

impl ListAllDataRequest {
    fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self {
            client,
            limit: None,
            offset: None,
        }
    }

    /// The number of items to return
    pub fn limit(mut self, value: i64) -> Self {
        self.limit = Some(value);
        self
    }

    /// The number of items to skip before starting to collect the result set
    pub fn offset(mut self, value: i64) -> Self {
        self.offset = Some(value);
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::PlanetsListAllDataResponse, crate::error::Error> {
        let path = "/planets".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.limit {
            query.push(("limit".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.offset {
            query.push(("offset".to_string(), crate::http::scalar_value(value)));
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::PlanetsListAllDataResponse, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::ScalarGalaxyClient,
    body: Option<crate::models::Planet>,
    idempotency_key: Option<String>,
}

impl CreateRequest {
    fn new(client: crate::client::ScalarGalaxyClient) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
        }
    }

    /// Planet
    pub fn body(mut self, value: crate::models::Planet) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = "/planets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        self.client
            .send::<crate::models::Planet, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequest {
    client: crate::client::ScalarGalaxyClient,
    planet_id: i64,
}

impl RetrieveRequest {
    fn new(client: crate::client::ScalarGalaxyClient, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = format!("/planets/{}", crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id)));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::Planet, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Sometimes you make mistakes, that's fine. No worries, you can update all planets.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequest {
    client: crate::client::ScalarGalaxyClient,
    planet_id: i64,
    body: Option<crate::models::Planet>,
    idempotency_key: Option<String>,
}

impl UpdateRequest {
    fn new(client: crate::client::ScalarGalaxyClient, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            body: None,
            idempotency_key: None,
        }
    }

    /// New information about the planet
    pub fn body(mut self, value: crate::models::Planet) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = format!("/planets/{}", crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id)));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        self.client
            .send::<crate::models::Planet, _>(reqwest::Method::PUT, &path, &query, &headers, body, true)
            .await
    }
}
/// This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequest {
    client: crate::client::ScalarGalaxyClient,
    planet_id: i64,
    idempotency_key: Option<String>,
}

impl DeleteRequest {
    fn new(client: crate::client::ScalarGalaxyClient, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<(), crate::error::Error> {
        let path = format!("/planets/{}", crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id)));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send_empty(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
/// Got a crazy good photo of a planet? Share it with the world!
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UploadImageRequest {
    client: crate::client::ScalarGalaxyClient,
    planet_id: i64,
    body: Option<crate::models::PlanetsUploadImageBody>,
    idempotency_key: Option<String>,
}

impl UploadImageRequest {
    fn new(client: crate::client::ScalarGalaxyClient, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            body: None,
            idempotency_key: None,
        }
    }

    /// Image to upload
    pub fn body(mut self, value: crate::models::PlanetsUploadImageBody) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::PlanetsUploadImageResponse, crate::error::Error> {
        let path = format!("/planets/{}/image", crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id)));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        self.client
            .send_multipart::<crate::models::PlanetsUploadImageResponse, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
