// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Runtime smoke test: drives every synthesizable operation once.
//!
//! Set `SCALAR_BASE_URL` (and any credential env vars) to point the client at a
//! server and actually send requests; with it unset the test is a no-op, so a
//! bare `cargo test` just confirms the generated surface compiles.
#![allow(unused)]

use scalargalaxy_rust::*;

#[tokio::test]
async fn smoke() {
    if std::env::var("SCALAR_BASE_URL").is_err() {
        return;
    }
    let client = ScalarGalaxyClient::from_env().expect("client builds from environment");
    let mut failures: Vec<String> = Vec::new();
    {
        let result: Result<(), Error> = async {
            let _ = client.planets().list_all_data().send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "GET /planets"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.planets().create().send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "POST /planets"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.planets().retrieve(1).send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "GET /planets/{planetId}"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.planets().update(1).send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "PUT /planets/{planetId}"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            client.planets().delete(1).send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "DELETE /planets/{planetId}"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.planets().upload_image(1).send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "POST /planets/{planetId}/image"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.authentication().create_user().send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "POST /user/signup"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.authentication().create_token().send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "POST /auth/token"));
            }
        }
    }
    {
        let result: Result<(), Error> = async {
            let _ = client.authentication().list_me().send().await?;
            Ok(())
        }
        .await;
        if let Err(error) = result {
            if is_smoke_failure(&error) {
                failures.push(format!("{}: {error}", "GET /me"));
            }
        }
    }
    assert!(failures.is_empty(), "smoke failures:\n{}", failures.join("\n"));
}

/// A smoke failure is a plumbing problem — the request could not be sent or
/// the client was misconfigured. An API error (a response with a non-success
/// status) or a decode error means the request reached the server and came
/// back, which is what this smoke verifies; the response body itself is the
/// server's concern, not the SDK's.
fn is_smoke_failure(error: &Error) -> bool {
    matches!(error, Error::Transport(_) | Error::Config(_) | Error::MissingParameter(_))
}
