// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Report-writing smoke harness: drives every synthesizable operation once
//! and writes a per-operation JSON report.
//!
//! Run it with `cargo run --example smoke-test`. The generator runs this
//! example against a mock server and reads the JSON report written to the
//! path named by `SCALAR_SMOKE_REPORT`, honoring an optional
//! `SCALAR_SMOKE_FILTER` of comma-separated operation/path substrings.
#![allow(unused)]

use scalargalaxy_rust::*;

#[derive(serde::Serialize)]
struct SmokeResult {
    operation: String,
    method: String,
    path: String,
    status: String,
    #[serde(rename = "durationMs")]
    duration_ms: i64,
    #[serde(skip_serializing_if = "String::is_empty")]
    error: String,
}

#[derive(serde::Serialize)]
struct SmokeReport {
    total: usize,
    failed: usize,
    results: Vec<SmokeResult>,
}

/// Whether an operation/path is selected by the optional comma-separated
/// `SCALAR_SMOKE_FILTER`; with no filter every operation runs.
fn selected(filter: &Option<Vec<String>>, operation: &str, path: &str) -> bool {
    match filter {
        None => true,
        Some(needles) => needles
            .iter()
            .any(|needle| operation.contains(needle.as_str()) || path.contains(needle.as_str())),
    }
}

#[tokio::main]
async fn main() {
    let report_path = std::env::var("SCALAR_SMOKE_REPORT").ok();
    let filter = std::env::var("SCALAR_SMOKE_FILTER").ok().map(|raw| {
        raw.split(',')
            .map(|needle| needle.trim().to_string())
            .filter(|needle| !needle.is_empty())
            .collect::<Vec<_>>()
    });
    let client = ScalarGalaxyClient::from_env().expect("client builds from environment");
    let mut results: Vec<SmokeResult> = Vec::new();
    if selected(&filter, "listAllData", "/planets") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.planets().list_all_data().send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "listAllData".to_string(),
            method: "GET".to_string(),
            path: "/planets".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "create", "/planets") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.planets().create().send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "create".to_string(),
            method: "POST".to_string(),
            path: "/planets".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "retrieve", "/planets/{planetId}") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.planets().retrieve(1).send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "retrieve".to_string(),
            method: "GET".to_string(),
            path: "/planets/{planetId}".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "update", "/planets/{planetId}") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.planets().update(1).send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "update".to_string(),
            method: "PUT".to_string(),
            path: "/planets/{planetId}".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "delete", "/planets/{planetId}") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            client.planets().delete(1).send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "delete".to_string(),
            method: "DELETE".to_string(),
            path: "/planets/{planetId}".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "uploadImage", "/planets/{planetId}/image") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.planets().upload_image(1).send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "uploadImage".to_string(),
            method: "POST".to_string(),
            path: "/planets/{planetId}/image".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "createUser", "/user/signup") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.authentication().create_user().send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "createUser".to_string(),
            method: "POST".to_string(),
            path: "/user/signup".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "createToken", "/auth/token") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.authentication().create_token().send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "createToken".to_string(),
            method: "POST".to_string(),
            path: "/auth/token".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "listMe", "/me") {
        let started = std::time::Instant::now();
        let result: Result<(), Error> = async {
            let _ = client.authentication().list_me().send().await?;
            Ok(())
        }
        .await;
        let duration_ms = started.elapsed().as_millis() as i64;
        let (status, error) = match result {
            Ok(()) => ("passed", String::new()),
            Err(error) if is_smoke_failure(&error) => ("failed", format!("{error}")),
            // A response came back (API error or decode mismatch): the request
            // reached the server, which is what this smoke verifies.
            Err(_) => ("passed", String::new()),
        };
        results.push(SmokeResult {
            operation: "listMe".to_string(),
            method: "GET".to_string(),
            path: "/me".to_string(),
            status: status.to_string(),
            duration_ms,
            error,
        });
    }
    if selected(&filter, "create", "/celestial-bodies") {
        results.push(SmokeResult {
            operation: "create".to_string(),
            method: "POST".to_string(),
            path: "/celestial-bodies".to_string(),
            status: "skipped".to_string(),
            duration_ms: 0,
            error: "required request arguments could not be synthesized into a compiling value".to_string(),
        });
    }

    let passed = results.iter().filter(|result| result.status == "passed").count();
    let failed = results.iter().filter(|result| result.status == "failed").count();
    let report = SmokeReport { total: results.len(), failed, results };

    if let Some(path) = report_path {
        let json = serde_json::to_string(&report).expect("serialize smoke report");
        std::fs::write(&path, json).expect("write smoke report");
    } else {
        for result in &report.results {
            match result.status.as_str() {
                "passed" => println!("PASS {} ({} {})", result.operation, result.method, result.path),
                "skipped" => println!("SKIP {} ({} {}): {}", result.operation, result.method, result.path, result.error),
                _ => eprintln!("FAIL {} ({} {})\n{}", result.operation, result.method, result.path, result.error),
            }
        }
    }

    // A vacuous run (nothing passed: empty SDK or every operation skipped) fails, like the
    // shared runner. Skipped operations on their own never fail the run.
    if report.failed > 0 || passed == 0 {
        std::process::exit(1);
    }
}

/// A smoke failure is a plumbing problem — the request could not be sent or
/// the client was misconfigured. An API error (a response with a non-success
/// status) or a decode error means the request reached the server and came
/// back, which is what this smoke verifies; the synthetic response body the
/// mock returns is not the SDK's concern.
fn is_smoke_failure(error: &Error) -> bool {
    matches!(error, Error::Transport(_) | Error::Config(_) | Error::MissingParameter(_))
}
