// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The ScalarGalaxyClient API client.

use std::sync::Arc;
use std::time::Duration;

use reqwest::Method;
use serde::de::DeserializeOwned;
use serde::Serialize;

use crate::error::Error;
use crate::http::{self, RetryPolicy};

const DEFAULT_MAX_RETRIES: u32 = 2;
const USER_AGENT: &str = concat!("scalargalaxy-rust/", env!("CARGO_PKG_VERSION"));
const IDEMPOTENCY_HEADER: &str = "Idempotency-Key";

/// A named API environment with a preset base URL.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[non_exhaustive]
pub enum Environment {
    /// The `production` environment.
    #[default]
    Production,
    /// The `responds_with_your_request_data` environment.
    RespondsWithYourRequestData,
}

impl Environment {
    /// The base URL for this environment.
    pub fn base_url(self) -> &'static str {
        match self {
            Self::Production => "https://galaxy.scalar.com",
            Self::RespondsWithYourRequestData => "{protocol}://void.scalar.com/{path}",
        }
    }
}

/// Credentials applied to every outgoing request.
#[derive(Clone, Default)]
struct Auth {
    bearer_token: Option<String>,
    username: Option<String>,
    password: Option<String>,
    api_key_header: Option<String>,
    api_key_query: Option<String>,
    api_key_cookie: Option<String>,
    access_token: Option<String>,
}

impl Auth {
    /// Applies the configured credentials to a request builder.
    fn apply(&self, mut builder: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        if self.bearer_token.is_some() {
            if let Some(value) = &self.bearer_token {
                builder = builder.bearer_auth(value);
            }
        } else if self.username.is_some() && self.password.is_some() {
            if let Some(value) = &self.username {
                builder = builder.basic_auth(value, self.password.as_ref());
            }
        } else if self.api_key_query.is_some() {
            if let Some(value) = &self.api_key_query {
                builder = builder.query(&[("api_key", value)]);
            }
        } else if self.api_key_header.is_some() {
            if let Some(value) = &self.api_key_header {
                builder = builder.header("X-API-Key", value);
            }
        } else if self.api_key_cookie.is_some() {
            if let Some(value) = &self.api_key_cookie {
                builder = builder.header(reqwest::header::COOKIE, format!("{}={}", "api_key", value));
            }
        } else if self.access_token.is_some() {
            if let Some(value) = &self.access_token {
                builder = builder.bearer_auth(value);
            }
        } else if self.access_token.is_some() {
            if let Some(value) = &self.access_token {
                builder = builder.bearer_auth(value);
            }
        }
        builder
    }
}

/// Shared client state held behind an `Arc` so cloning a client is cheap.
struct Inner {
    http: reqwest::Client,
    base_url: url::Url,
    auth: Auth,
    retry: RetryPolicy,
    /// Applied per-request so a caller-supplied `http_client` still honors the
    /// builder `timeout` (a prebuilt `reqwest::Client` cannot be reconfigured).
    timeout: Option<Duration>,
}

/// How a request body is serialized onto the wire.
#[derive(Clone, Copy)]
enum ContentEncoding {
    /// `application/json` body.
    Json,
    /// `multipart/form-data` body.
    Multipart,
}

/// Builds a `multipart/form-data` form from a JSON object body.
///
/// Each top-level field becomes a text part: string values are sent verbatim
/// and other scalars use their JSON representation, while nested
/// objects/arrays are JSON-encoded so no information is lost.
fn value_to_multipart(body: &serde_json::Value) -> reqwest::multipart::Form {
    let mut form = reqwest::multipart::Form::new();
    if let Some(object) = body.as_object() {
        for (key, value) in object {
            let part = match value {
                serde_json::Value::String(text) => text.clone(),
                serde_json::Value::Null => String::new(),
                other => other.to_string(),
            };
            form = form.text(key.clone(), part);
        }
    }
    form
}

/// Asynchronous client for the ScalarGalaxyClient API.
///
/// Cloning is cheap: all state is shared behind an `Arc`. Construct one with
/// [`ScalarGalaxyClient::builder`] or [`ScalarGalaxyClient::from_env`].
#[derive(Clone)]
pub struct ScalarGalaxyClient {
    inner: Arc<Inner>,
}

impl ScalarGalaxyClient {
    /// Starts building a client with the fluent builder.
    pub fn builder() -> ScalarGalaxyClientBuilder {
        ScalarGalaxyClientBuilder::new()
    }

    /// Builds a client, reading credentials from the environment.
    ///
    /// Each credential is read from its conventional environment variable;
    /// missing variables are simply left unset.
    pub fn from_env() -> Result<Self, Error> {
        let mut builder = Self::builder();
        if let Ok(value) = std::env::var("SCALAR_BASE_URL") {
            builder = builder.base_url(value);
        }
        if let Ok(value) = std::env::var("SCALAR_BEARER_TOKEN") {
            builder = builder.bearer_token(value);
        }
        if let Ok(value) = std::env::var("SCALAR_USERNAME") {
            builder = builder.username(value);
        }
        if let Ok(value) = std::env::var("SCALAR_PASSWORD") {
            builder = builder.password(value);
        }
        if let Ok(value) = std::env::var("SCALAR_API_KEY_HEADER") {
            builder = builder.api_key_header(value);
        }
        if let Ok(value) = std::env::var("SCALAR_API_KEY_QUERY") {
            builder = builder.api_key_query(value);
        }
        if let Ok(value) = std::env::var("SCALAR_API_KEY_COOKIE") {
            builder = builder.api_key_cookie(value);
        }
        if let Ok(value) = std::env::var("SCALAR_ACCESS_TOKEN") {
            builder = builder.access_token(value);
        }
        builder.build()
    }
}

impl std::fmt::Debug for ScalarGalaxyClient {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ScalarGalaxyClient")
            .field("base_url", &self.inner.base_url.as_str())
            .field("retry", &self.inner.retry)
            .field("timeout", &self.inner.timeout)
            .finish_non_exhaustive()
    }
}

#[allow(dead_code, clippy::too_many_arguments)]
impl ScalarGalaxyClient {
    /// Builds, authenticates, and sends a request, decoding a JSON response.
    pub(crate) async fn send<T: DeserializeOwned, B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
    ) -> Result<T, Error> {
        let response = self.dispatch(method, path, query, headers, body, apply_auth, ContentEncoding::Json).await?;
        http::decode_json(response).await
    }

    /// Like [`send`](Self::send) but for operations that return no content.
    pub(crate) async fn send_empty<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
    ) -> Result<(), Error> {
        let response = self.dispatch(method, path, query, headers, body, apply_auth, ContentEncoding::Json).await?;
        http::decode_empty(response).await
    }

    /// Like [`send`](Self::send) but encodes the body as `multipart/form-data`.
    pub(crate) async fn send_multipart<T: DeserializeOwned, B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
    ) -> Result<T, Error> {
        let response = self.dispatch(method, path, query, headers, body, apply_auth, ContentEncoding::Multipart).await?;
        http::decode_json(response).await
    }

    /// Sends a request and returns the raw response, for streaming operations.
    pub(crate) async fn send_raw<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
    ) -> Result<reqwest::Response, Error> {
        self.dispatch(method, path, query, headers, body, apply_auth, ContentEncoding::Json).await
    }

    /// Assembles a request (URL, query, headers, body, auth) and sends it with retries.
    async fn dispatch<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
        content: ContentEncoding,
    ) -> Result<reqwest::Response, Error> {
        let url = self
            .inner
            .base_url
            .join(path.trim_start_matches('/'))
            .map_err(|error| Error::Config(error.to_string()))?;
        let mut builder = self.inner.http.request(method, url);
        if let Some(timeout) = self.inner.timeout {
            builder = builder.timeout(timeout);
        }
        if !query.is_empty() {
            builder = builder.query(query);
        }
        for (name, value) in headers {
            builder = builder.header(name, value);
        }
        if let Some(body) = body {
            builder = match content {
                ContentEncoding::Json => builder.json(body),
                ContentEncoding::Multipart => {
                    let value = serde_json::to_value(body)?;
                    builder.multipart(value_to_multipart(&value))
                }
            };
        }
        let keyed = headers.iter().any(|(name, _)| name.eq_ignore_ascii_case(IDEMPOTENCY_HEADER));
        if apply_auth {
            builder = self.inner.auth.apply(builder);
        }
        let request = builder.build()?;
        http::send_with_retries(&self.inner.http, request, &self.inner.retry, keyed).await
    }
}

/// Fluent builder for [`ScalarGalaxyClient`].
#[derive(Default)]
pub struct ScalarGalaxyClientBuilder {
    base_url: Option<String>,
    environment: Option<Environment>,
    timeout: Option<Duration>,
    max_retries: Option<u32>,
    http_client: Option<reqwest::Client>,
    bearer_token: Option<String>,
    username: Option<String>,
    password: Option<String>,
    api_key_header: Option<String>,
    api_key_query: Option<String>,
    api_key_cookie: Option<String>,
    access_token: Option<String>,
}

impl ScalarGalaxyClientBuilder {
    /// Creates an empty builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Overrides the base URL the client sends requests to.
    pub fn base_url(mut self, base_url: impl Into<String>) -> Self {
        self.base_url = Some(base_url.into());
        self
    }

    /// Selects a named environment, setting the base URL.
    pub fn environment(mut self, environment: Environment) -> Self {
        self.environment = Some(environment);
        self
    }

    /// Sets the per-request timeout.
    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Sets the maximum number of retry attempts for transient failures.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Supplies a preconfigured `reqwest::Client` (proxies, custom TLS, etc.).
    pub fn http_client(mut self, http_client: reqwest::Client) -> Self {
        self.http_client = Some(http_client);
        self
    }

    /// JWT Bearer token authentication
    pub fn bearer_token(mut self, value: impl Into<String>) -> Self {
        self.bearer_token = Some(value.into());
        self
    }

    /// Basic HTTP authentication
    pub fn username(mut self, value: impl Into<String>) -> Self {
        self.username = Some(value.into());
        self
    }

    /// Basic HTTP authentication
    pub fn password(mut self, value: impl Into<String>) -> Self {
        self.password = Some(value.into());
        self
    }

    /// API key request header
    pub fn api_key_header(mut self, value: impl Into<String>) -> Self {
        self.api_key_header = Some(value.into());
        self
    }

    /// API key query parameter
    pub fn api_key_query(mut self, value: impl Into<String>) -> Self {
        self.api_key_query = Some(value.into());
        self
    }

    /// API key browser cookie
    pub fn api_key_cookie(mut self, value: impl Into<String>) -> Self {
        self.api_key_cookie = Some(value.into());
        self
    }

    /// OAuth 2.0 authentication
    pub fn access_token(mut self, value: impl Into<String>) -> Self {
        self.access_token = Some(value.into());
        self
    }

    /// Builds the client, resolving the base URL and HTTP stack.
    pub fn build(self) -> Result<ScalarGalaxyClient, Error> {
        let base_url = self
            .base_url
            .unwrap_or_else(|| self.environment.unwrap_or_default().base_url().to_string());
        let base_url = normalize_base_url(&base_url)?;
        let http = match self.http_client {
            Some(http) => http,
            None => reqwest::Client::builder().user_agent(USER_AGENT).build()?,
        };
        let retry = RetryPolicy::new(self.max_retries.unwrap_or(DEFAULT_MAX_RETRIES));
        Ok(ScalarGalaxyClient {
            inner: Arc::new(Inner {
                http,
                base_url,
                auth: Auth {
                        bearer_token: self.bearer_token,
                        username: self.username,
                        password: self.password,
                        api_key_header: self.api_key_header,
                        api_key_query: self.api_key_query,
                        api_key_cookie: self.api_key_cookie,
                        access_token: self.access_token,
                },
                retry,
                timeout: self.timeout,
            }),
        })
    }
}

impl std::fmt::Debug for ScalarGalaxyClientBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ScalarGalaxyClientBuilder")
            .field("base_url", &self.base_url)
            .field("environment", &self.environment)
            .field("timeout", &self.timeout)
            .field("max_retries", &self.max_retries)
            .finish_non_exhaustive()
    }
}

/// Parses a base URL, ensuring a trailing slash so relative paths join correctly.
fn normalize_base_url(base_url: &str) -> Result<url::Url, Error> {
    let with_slash = if base_url.ends_with('/') {
        base_url.to_string()
    } else {
        format!("{base_url}/")
    };
    url::Url::parse(&with_slash).map_err(|error| Error::Config(error.to_string()))
}
