// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models.
#![allow(clippy::large_enum_variant)]

use serde::{Deserialize, Serialize};

/// A user
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Credentials to authenticate a user
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    pub email: String,
    pub password: String,
}

/// A token to authenticate a user
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Token {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

/// A celestial body which can be either a planet or a satellite
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CelestialBody {
    #[serde(rename = "planet")]
    Planet(Planet),
    #[serde(rename = "satellite")]
    Satellite(Satellite),
}

/// A planet in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Planet {
    pub id: i64,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    /// A score from 0 to 1 indicating potential habitability
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub habitability_index: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub physical_properties: Option<serde_json::Value>,
    /// Atmospheric composition
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub atmosphere: Option<Vec<serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discovered_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub satellites: Option<Vec<Satellite>>,
    /// A user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<User>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// URL which gets invoked upon a successful operation
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub success_callback_url: Option<String>,
    /// URL which gets invoked upon a failed operation
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_callback_url: Option<String>,
}

/// Every satellite in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Satellite {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Diameter in kilometers
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diameter: Option<f64>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orbit: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlanetsListAllDataResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<Planet>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<PlanetsListAllDataResponseMeta>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlanetsListAllDataResponseMeta {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlanetsUploadImageResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The URL where the uploaded image can be accessed
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Timestamp when the image was uploaded
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Size of the uploaded image in bytes
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
    /// The content type of the uploaded image
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlanetsUploadImageBody {
    /// The image file to upload
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationCreateUserBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub email: String,
    pub password: String,
}
