// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Inbound webhook event types and verification.

use crate::error::Error;

/// A decoded inbound webhook event.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum WebhookEvent {
    NewPlanet(serde_json::Value),
}

impl WebhookEvent {
    /// Parses a webhook payload, dispatching on the event-type string.
    ///
    /// `event_type` is the value the webhook delivers to identify the event
    /// (typically in a request header); `payload` is the raw JSON body.
    pub fn parse(event_type: &str, payload: &[u8]) -> Result<Self, Error> {
        match event_type {
        "newPlanet" => Ok(Self::NewPlanet(serde_json::from_slice(payload)?)),
            other => Err(Error::Config(format!("unrecognized webhook event type: {other}"))),
        }
    }
}
